### ISSUE TITLE
Error: Can't detect sandbox ID from the current URL

### ISSUE THREAD

**Issue by SourceCodeOpen** [NetEase/tango-playground#1]
As i  use caddy run this prebuild assets from github, and use the following command to carry out . 
`caddy_windows_amd64.exe file-server --root C:\Users\12509\Desktop\www\codesandbox --listen local.netease.com:8443`
Aflter that i open my browser to visit "https://local.netease.com:8443/" ,And open my Devtools find that
`
url-generator.js:239 Uncaught (in promise) Error: Can't detect sandbox ID from the current URL
    at t.getSandboxId (url-generator.js:239:15)
    at index.ts:95:16

`
What can i do?

**Comment by ccloli** [comment]
It's intended, because the sandbox is mainly used to be integrated with [Tango](https://github.com/NetEase/tango), the data needs to be run in sandbox (including the sandbox id) will be passed from the Tango Designer. So if you open the sandbox directly, it'll throw such error and shows nothing.

BTW please use the `Caddyfile` in [the codesandbox repo](https://github.com/NetEase/codesandbox-client/blob/master/Caddyfile), because a HTTP response header is required since Chrome 115. For details, please follow the [quick start guide](https://netease.github.io/tango/en/docs/designer/quick-start).

**Comment by SourceCodeOpen** [comment]
thanks,i have done it.but it still has some runtime exception,wait for a new version.

**Comment by ccloli** [comment]
Yep, there're still things need to be done for the opensource version. If you're interested, feel free to follow and ask in the main repository https://github.com/NetEase/tango , since this repo is mainly for hosting the demo site.
